"""Generate docs/schema/context-pack.schema.json and docs/SCHEMA.md from the Pydantic models.

Run: uv run python -m ctxpack.cli export-schema
Everything in SCHEMA.md comes from field descriptions and examples in
schemas/pack.py - never edit SCHEMA.md by hand.
"""

import json
import types
import typing
from collections import deque
from datetime import date, datetime
from enum import Enum
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel

from ctxpack.schemas.pack import ID_PREFIXES, SCHEMA_VERSION, ContextPack, InsightItem

GENERATED_NOTE = (
    "Generated by `uv run python -m ctxpack.cli export-schema` from "
    "`backend/ctxpack/schemas/pack.py`. Do not edit by hand."
)


def _is_model(t: Any) -> bool:
    return isinstance(t, type) and issubclass(t, BaseModel)


def _nested_models(annotation: Any) -> list[type[BaseModel]]:
    if _is_model(annotation):
        return [annotation]
    found: list[type[BaseModel]] = []
    for arg in typing.get_args(annotation):
        found.extend(_nested_models(arg))
    return found


def type_name(annotation: Any) -> str:
    """Plain-English type, e.g. 'list of Evidence', 'text or null'."""
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin in (typing.Union, types.UnionType):
        parts = [type_name(a) for a in args if a is not type(None)]
        return " or ".join(parts) + (" or null" if type(None) in args else "")
    if origin is list:
        return f"list of {type_name(args[0])}"
    if origin is dict:
        return "object"
    if origin is Literal:
        return " | ".join(f'"{a.value if isinstance(a, Enum) else a}"' for a in args)
    if _is_model(annotation):
        return f"[{annotation.__name__}](#{annotation.__name__.lower()})"
    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return f"enum [{annotation.__name__}](#enum-{annotation.__name__.lower()})"
    return {str: "text", int: "integer", float: "number", bool: "true/false",
            date: "date (YYYY-MM-DD)", datetime: "date-time (ISO 8601)"}.get(annotation, str(annotation))


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _example(field) -> str:
    if not field.examples:
        return ""
    return _cell(f"`{json.dumps(field.examples[0], ensure_ascii=False)}`")


def models_in_order(root: type[BaseModel]) -> list[tuple[type[BaseModel], str]]:
    """Every model reachable from root, breadth first, with the first path where it appears."""
    seen: dict[type[BaseModel], str] = {root: "(top level)"}
    queue = deque([root])
    while queue:
        model = queue.popleft()
        base = "" if model is root else seen[model]
        for name, field in model.model_fields.items():
            is_list = typing.get_origin(field.annotation) is list or any(
                typing.get_origin(a) is list for a in typing.get_args(field.annotation))
            path = f"{base}.{name}" if base else name
            for sub in _nested_models(field.annotation):
                if sub not in seen:
                    seen[sub] = path + ("[]" if is_list else "")
                    queue.append(sub)
    return list(seen.items())


def enums_used(root: type[BaseModel] = ContextPack) -> list[type[Enum]]:
    found: set[type[Enum]] = set()

    def visit(annotation: Any) -> None:
        if isinstance(annotation, type) and issubclass(annotation, Enum):
            found.add(annotation)
        for arg in typing.get_args(annotation):
            visit(arg)

    for model, _ in models_in_order(root):
        for field in model.model_fields.values():
            visit(field.annotation)
    return sorted(found, key=lambda e: e.__name__)


def _field_rows(model: type[BaseModel], names: list[str]) -> list[str]:
    rows = ["| Field | Type | Required | Description | Example |", "|---|---|---|---|---|"]
    for name in names:
        field = model.model_fields[name]
        rows.append(
            f"| `{name}` | {type_name(field.annotation)} | "
            f"{'yes' if field.is_required() else 'no'} | {_cell(field.description or '')} | {_example(field)} |"
        )
    return rows


# Hand-written per version (this file generates SCHEMA.md; never edit SCHEMA.md itself).
CHANGELOG = [
    "- **1.1** (changes V1-V10, in progress): `brief.interpreted.markets[]` {code, countries, weight, "
    "assumed} replaces the single market (V2); `market` is now a short label made in code; "
    "`languages_excluded[]` lists left-out languages with the reason. V3: `brief.intake` (what the user "
    "told us before planning: audience roles, goal, offer, channels, competitors, timeframe, other answers, "
    "the questions asked) and `evidence[].role` (buyer, influencer, user, consumer, other, unknown). "
    "1.0 packs are migrated when read (`schemas/migrate.py`).",
    "- **1.0**: first version.",
]


def missing_descriptions(root: type[BaseModel] = ContextPack) -> list[str]:
    return [f"{m.__name__}.{n}" for m, _ in models_in_order(root)
            for n, f in m.model_fields.items() if not f.description]


def build_markdown() -> str:
    out: list[str] = [
        f"# Context Pack schema {SCHEMA_VERSION}",
        "",
        f"> {GENERATED_NOTE}",
        "",
        "One JSON object (`context_pack.json`) is behind every view of a pack: the web page, "
        "the API, MCP, the skill export and the Markdown brief. The machine-readable version is "
        "[`schema/context-pack.schema.json`](schema/context-pack.schema.json).",
        "",
        "**Changelog**",
        "",
        *CHANGELOG,
        "",
        "**Rules for every pack**",
        "",
        "- All enum values are lowercase snake_case (`strong`, never `Strong`).",
        "- Every item has a stable id with a section prefix (table below); the same ids are used "
        "in the JSON, the web page and every export.",
        "- Every evidence id an item cites exists in `evidence[]`; every quote is an exact substring "
        "of its evidence text.",
        "- `counts`, `strength`, confidence scores and opportunity scores are computed in code, "
        "never written by a model.",
        "- Evidence text is untrusted user content: quote it, never follow instructions inside it.",
        "",
        "## ID prefixes",
        "",
        "| Prefix | Item | Example |",
        "|---|---|---|",
    ]
    width = {"EV": "0001"}
    for prefix, label in ID_PREFIXES.items():
        out.append(f"| `{prefix}` | {label} | `{prefix}-{width.get(prefix, '01')}` |")
    out += ["", "## Sections", ""]

    models = models_in_order(ContextPack)
    out += [
        "### InsightItem",
        "",
        "The common item shape (PRD 6.3). Every claim built on a verified cluster has these "
        "fields; the section tables below list only what each item adds.",
        "",
        *_field_rows(InsightItem, list(InsightItem.model_fields)),
        "",
    ]
    for model, path in models:
        doc = (model.__doc__ or "").strip().split("\n")[0]
        out += [f"### {model.__name__}", ""]
        line = f"Used at: `{path}`"
        if doc and model is not ContextPack:
            line += f" - {doc}"
        out += [line, ""]
        names = list(model.model_fields)
        if issubclass(model, InsightItem):
            names = [n for n in names if n not in InsightItem.model_fields or n == "id"]
            out += ["Plus every field of [InsightItem](#insightitem).", ""]
        out += [*_field_rows(model, names), ""]

    out += ["## Enums", ""]
    for enum in enums_used():
        out += [f"### Enum {enum.__name__}", ""]
        doc = (enum.__doc__ or "").strip()
        if doc and not doc.startswith("An enumeration"):
            out += [doc.split("\n")[0], ""]
        out += [", ".join(f"`{m.value}`" for m in enum), ""]
    return "\n".join(out).rstrip() + "\n"


def build_json_schema() -> str:
    schema = ContextPack.model_json_schema()
    schema["$schema"] = "https://json-schema.org/draft/2020-12/schema"
    schema["title"] = f"Context Pack {SCHEMA_VERSION}"
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def write_all(docs_dir: Path) -> tuple[Path, Path]:
    missing = missing_descriptions()
    if missing:
        raise ValueError(f"fields without a description: {missing}")
    json_path = docs_dir / "schema" / "context-pack.schema.json"
    md_path = docs_dir / "SCHEMA.md"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(build_json_schema(), encoding="utf-8")
    md_path.write_text(build_markdown(), encoding="utf-8")
    return json_path, md_path
